[pytest]
#--alluredir ./temp/allure/reports
addopts = -vs
testpaths = ./API_test/test_cases
python_files = test_*.py
python_classes = Test*
python_functions = test*
markers =
    smoke:冒烟用例
    personalOrder:个人订单用例
    enterpriseOrder:企业订单用例
    subscription_preaudit: 订阅预审用例
    preaudit: 预审用例



